name: "New Recipe"
description: "Add a new recipe via GitHub issue form."
labels: []
body:
  - type: input
    id: short_description
    attributes:
      label: "Short Description"
      description: "Provide a brief summary of the recipe."
      placeholder: "e.g., A classic Italian pizza topped with fresh mozzarella and basil."

  - type: dropdown
    id: category
    attributes:
      label: "Category"
      description: "Select the category that best fits your recipe."
      options:
        - "Main Course"
        - "Side Dish"
        - "Appetizer"
        - "Dessert"
        - "Breakfast"
        - "Soup"
        - "Salad"
        - "Snack"
        - "Beverage"
        - "Sauce/Condiment"
        - "Bread/Dough"
    validations:
      required: true

  - type: input
    id: portions
    attributes:
      label: Portions
      description: "Provide the number of portions the ingredients below make."
      value: 1
    validations:
      required: true

  - type: input
    id: variants
    attributes:
      label: Variants
      description: "Provide comma-separated list of variants if more than one is described."

  - type: textarea
    id: ingredients
    attributes:
      label: "Ingredients"
      description: "List all the ingredients needed for the recipe. Use one ingredient per line."
      placeholder: "- 2 cups of flour\n- 1 tsp of yeast\n- 1/2 tsp of salt"
    validations:  
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps"
      description: "Provide the step-by-step instructions for preparing the recipe."
      placeholder: "1. Combine the flour, yeast, and salt.\n2. Add water and knead the dough.\n3. Let the dough rise for 1 hour."
    validations:  
      required: true
